# Generated by Django 3.2.8 on 2021-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.CharField(default='100,000', max_length=100),
        ),
    ]
