# Generated by Django 3.2.8 on 2021-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=10),
        ),
    ]
