# Generated by Django 3.2.8 on 2021-10-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.CharField(default='100,000', max_length=100),
        ),
    ]
