# Generated by Django 3.2.8 on 2021-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211009_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=3, default=100000, max_digits=10),
        ),
    ]
