# Generated by Django 3.2.7 on 2021-10-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priorityofproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_like_nums',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productandhashtag',
            old_name='hashtag_id',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='productandhashtag',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoy_id',
            new_name='categoy',
        ),
    ]
