# Generated by Django 3.2.7 on 2021-10-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAndHashtag',
            new_name='ProductsHashtag',
        ),
        migrations.AlterModelTable(
            name='productshashtag',
            table='products_hashtag',
        ),
    ]
