# Generated by Django 3.2.7 on 2021-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdetailattrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailattrs',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
