# Generated by Django 3.2.7 on 2021-10-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productsmainimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.menus'),
        ),
        migrations.AlterField(
            model_name='productdetailattrs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_attrs', to='product.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categories'),
        ),
        migrations.AlterField(
            model_name='productshashtag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_hashtag', to='product.products'),
        ),
        migrations.AlterField(
            model_name='productsmainimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_main_images', to='product.products'),
        ),
    ]
