# Generated by Django 3.2.8 on 2021-10-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('product', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Carts',
        ),
    ]
